services:
  - type: web
    name: your-app-name
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false  # This tells Render to use the value from the dashboard
      - key: PYTHON_VERSION
        value: 3.9.0 